---
title: ".hi[EC 103--004]"
subtitle: ".b[Problem Set 1]"
author: ".b[Prof. Santetti] <br> Spring 2024"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'a-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
layout: true
class: clear
---

<br><br><br><br><br><br><br><br><br><br>

.hi[.mono[INSTRUCTIONS]]: Carefully read all problems. 


<br><br>

Recall that group work is *strongly recommended.*

<br><br><br>


.right[.hi[Have fun!]]


---
class: clear



## Problem 1

<br>

Consider the following transactions:

(a) A dealer sells US$500 worth of illegal heroin.

(b) Subaru builds a new plant in Detroit.

(c) You buy an used copy of *Lord of the Rings*.

(d) Apple issues new shares of stock to finance the construction of a new plant.

(e) Your grandfather wins US$5 million in the lottery.

(f) You buy a new issue of Joy Division's *Unknown Pleasures* LP.

(g) A pizzeria buys 30 pounds of pepperoni, holds it in inventory for 2 weeks, and then uses it to make pizza (which it sells).

(h) You spend the weekend mowing your lawn.

(i) A US company located in Prague sells US$80 thousand worth of its product in the local market.

(j) You buy a ticket to a concert in NYC, but you are not able to make it.

Which of these transactions will **not** be counted in the US's Gross Domestic Product (GDP)? Explain why for each case.

---
class: clear

## Problem 2

<br>

Consider the following economic data for country .mono[YYZ] for a given year:

<br>

```{r, echo=F, message=FALSE, warning=FALSE}
library(tidyverse)
library(kableExtra)

yyz <- tibble(
  "Category" = c("Nondurable goods", "Residential investment", "Structures (private)", 
                 "Public healthcare", "Imports", "Services", "Exports", "Illegal drug trafficking"),
  "Value ($ millions)" = c(500, 150.70, 275.60, 400, 380, 560.80, 420, 15.45) 
)


yyz %>% 
  kable(digits = 2)


```

<br>

(a) Calculate aggregate consumption and investment for this economy. Show your calculations.

(b) Calculate aggregate government expenditures and the trade balance for this economy. Show your calculations.

(c) What is .mono[YYZ]'s Gross Domestic Product for this year? Show your calculations. 



---
class: clear


## Problem 3

<br>


For this problem, we will use the [`Human Development Report 2021-2022`](https://hdr.undp.org/content/human-development-report-2021-22), released by the United Nations in September/2022.

For the following parts, carefully read the report's section `Rising insecurity amid unprecedented material prosperity-for some`, between pages 31 and 34 of the PDF document that you can see [`here`](https://hdr.undp.org/system/files/documents/global-report-document/hdr2021-22pdf_1.pdf).

(a) What method has the report employed to conclude that today's distress levels are unprecedented? 

(b) Which group of countries has observed the largest increases in perceived insecurity levels?

(c) Given your answer to part (b), list and discuss possible reasons for this result. Make sure to relate the income level of these countries with higher perceived insecurity in recent times. 

(d) What groups have been experiencing the highest levels of negative affect (i.e., stress, sadness, anger or worry) over the past years, based on the text and figure 1.6?

(e) In the report's methodology, what is the threshold level for *extreme poverty*? Also, between 2020 and 2021, how many more people became part of this group?


---
class: clear


## Problem 4

<br>

The next 10 statements are either .b[True] or .b[False]. If .b[false], provide a brief explanation why.

<br>

(a) *Gross National Product* (GNP) includes goods and services produced abroad by local companies.

(b) If a *Japanese* firm provides a consulting service in the U.S., expenditures on that service will count towards the Japanese *Gross Domestic Product* (GDP).

(c) *Aggregate investment* (*I*) includes the purchases of financial stocks and bonds by households.

(d) *Government expenditures* (*G*) includes expenditures undertaken by federal, state, and local instances.

(e) If a country shows a trade *surplus*, its exports (*X*) are greater than its imports (*M*).

(f) If a country's *nominal* GDP rises, it implies that its *real* GDP will rise.

(g) The *exchange rate* is the value of one currency in terms of another currency.

(h) GDP *per capita* is measured by dividing a country's GDP by its adult population.

(i) Government *cash transfers* are included in the measurement of a country's Gross Domestic Product.

(j) The same good/service can be an *intermediate* or a *final* good/service, depending on the context.


---
exclude:true
